### ISSUE TITLE
BUG: for parallelised execution, `execute_multiple()` does not properly set identifiercrop-region to whole-image region when ident is not cropped

### ISSUE THREAD

**Issue by Gewerd-Strauss** [Claudius-Appel/duflor.gui#83]
this will break in parallelisation with a cryptic error since required values are unassigned

**Comment by Claudius-Appel** [comment]
See 

https://github.com/Claudius-Appel/duflor.gui/blob/cea8b78a068528d25232a246bb9db4f1864e8be5/R/execute_multiple.R#L106-L124
